version: v1.0.0.{build}
os: Visual Studio 2015

init:
- cmd: >-
- ps: .\build\dotnet-latest.ps1
    set PATH=C:\Program Files\dotnet\bin;%PATH%

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '1.0.0.{build}'
  assembly_file_version: '1.0.0.{build}'

before_build:
- cmd: >-
    dotnet restore src\ImageProcessorCore

    cd build

    npm install

    node appveyor-project-version-patch.js

    cd..

build_script:
- cmd: >-
    dotnet pack src\ImageProcessorCore --configuration Release --output "artifacts\bin\ImageProcessorCore"

test: off

artifacts:
- path: artifacts\bin\ImageProcessorCore\**\*.nupkg

deploy:
    # MyGet Deployment for builds & releases
 - provider: NuGet
   server: https://www.myget.org/F/imageprocessor/api/v2/package
   symbol_server: https://nuget.symbolsource.org/MyGet/imageprocessor
   api_key:
     secure: fz0rUrt3B1HczUC1ZehwVsrFSWX9WZGDQoueDztLte9/+yQG+BBU7UrO+coE8lUf
   artifact: /.*\.nupkg/
   on:
     branch: Core